json.id @notification_setting.id
json.user_id @notification_setting.user_id
json.account_id @notification_setting.account_id
json.all_email_flags @notification_setting.all_email_flags
json.selected_email_flags @notification_setting.selected_email_flags
json.all_push_flags @notification_setting.all_push_flags
json.selected_push_flags @notification_setting.selected_push_flags
json.notification_display_duration @notification_setting.notification_display_duration || 6
json.new_conversation_sound_enabled @notification_setting.new_conversation_sound_enabled
json.new_conversation_sound @notification_setting.new_conversation_sound
json.new_conversation_volume @notification_setting.new_conversation_volume
json.new_conversation_custom_sound_id @notification_setting.new_conversation_custom_sound_id
json.new_conversation_custom_sound_url @notification_setting.new_conversation_custom_sound&.file_url
json.new_message_sound_enabled @notification_setting.new_message_sound_enabled
json.new_message_sound @notification_setting.new_message_sound
json.new_message_volume @notification_setting.new_message_volume
json.new_message_custom_sound_id @notification_setting.new_message_custom_sound_id
json.new_message_custom_sound_url @notification_setting.new_message_custom_sound&.file_url
json.custom_sounds current_user.notification_sounds.with_attached_file.order(created_at: :desc).map(&:push_event_data)
